name = "TerraFirmaGreg-1.20.x"
author = "Exception, Xikaro"
version = "0.7.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0dbfe35c473546749f7492c6b3ff4269bb21ed2702af7442f6b436a4fcd1f985"

[versions]
forge = "47.2.6"
minecraft = "1.20.1"
