name = "TerraFirmaGreg-1.20.x"
author = "Exception, Xikaro"
version = "0.7.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b3b47c91aab8f7e4773aa8d926e00de3b93f64f5b02d9e1c7ea097f21994ddf0"

[versions]
forge = "47.2.6"
minecraft = "1.20.1"
