name = "TerraFirmaGreg-Modern"
author = "Exception, Xikaro"
version = "0.7.13"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cde85dc949f9f265ee7f80056ad70205b2a63f9915bae701bff617b0eeb220e9"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
